Repository GoogleCloudPlatform/functions-framework-nodejs, pull requests merged in 2019-09, with the labels that each got.

#81 fixes #33: Only listen to functionTarget.
  src/index.ts
  src/invoker.ts
  test/invoker.ts
Labels: cla: yes

#70 Docs Updates
  docs/README.md
  docs/debugging.md
  docs/events.md
Labels: cla: yes

#88 Release @google-cloud/functions-framework v1.3.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes

#90 fix: use empty string path when function source is not specified
  src/index.ts
Labels: cla: yes

#91 Release @google-cloud/functions-framework v1.3.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes

#94 Release @google-cloud/functions-framework v1.3.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes

#100 Changed curl command to include json content-type
  docs/README.md
Labels: cla: yes

#102 docs: add video about FF
  README.md
Labels: cla: yes, docs
